"""
test the times generated by gen_schedule_wait_times
"""
from lid_ds.sim import gen_schedule_wait_times
#from ../../lid_ds/sim/schedule import gen_schedule_wait_times
import itertools


def test_scheduler_times():
    """
    test wait_times in sum are less than max time
    """
    for _ in itertools.repeat(None, 1000):
        max_time = 100
        wait_times = gen_schedule_wait_times(max_time)
        time_sum = sum(map(float, wait_times))
        # print(wait_times)
        assert (time_sum < max_time)


test_scheduler_times()
